server:
  port: 8082

spring:
  datasource:
    bhpj:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://cdb-gby1wmoc.cd.tencentcdb.com:10026/bhpj?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: zfm123456
      initial-size: 2
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
